// ===== Curriculum =====
// Lesson ids are stable — saved user progress references them — so lessons are
// ordered by array position, not by id. Chord shapes live in ./chords.

export interface Lesson {
  id: string;
  title: string;
  subtitle: string;
  minutes: number;
  kicker?: string; // assigned automatically from position below
  objective: string;
  scripture?: { text: string; ref: string }; // King James Version, only where it truly fits
  chords?: string[]; // keys into CHORDS (see ./chords)
  progression?: { key: string; degrees: number[] };
  learn: { title: string; body: string }[];
  practice: string[];
  playAlong: string;
  tip?: string;
  theory?: string; // deeper music theory — used in the advanced modules
}

export interface Module {
  id: string;
  num: number;
  title: string;
  subtitle: string;
  lessons: Lesson[];
}

export const MODULES: Module[] = [
  {
    id: "m1",
    num: 1,
    title: "Foundations",
    subtitle: "Posture, hands & first notes",
    lessons: [
      {
        id: "m1l1",
        title: "Holding the Guitar",
        subtitle: "Classical posture and a relaxed hold",
        minutes: 8,
        objective: "Sit and hold the guitar so your hands are free to move without tension.",
        scripture: { text: "And let the beauty of the LORD our God be upon us: and establish thou the work of our hands upon us; yea, the work of our hands establish thou it.", ref: "Psalm 90:17" },
        learn: [
          { title: "Sit tall", body: "Sit forward on a firm chair, both feet flat. Rest the waist of the guitar on your right leg (or left leg with a footstool for full classical posture)." },
          { title: "Let the neck rise", body: "Angle the headstock up to about eye-level height. This keeps your fretting wrist straight instead of collapsed." },
          { title: "Relax your shoulders", body: "Your right forearm drapes over the top of the body. Neither hand should be holding the guitar up — the body and legs do that." },
        ],
        practice: [
          "Set up your posture, then let go with both hands for 5 seconds. If the guitar slides, adjust your hold until it balances on its own.",
          "Play any single string 10 times, resetting your posture between each. Aim for the same relaxed position every time.",
        ],
        playAlong: "Nothing to play yet — just get comfortable. A relaxed body is the foundation every other skill is built on.",
        tip: "Tension is the enemy. Check your shoulders every few minutes and let them drop.",
      },
      {
        id: "m1l2",
        title: "Naming the Strings",
        subtitle: "E A D G B E, low to high",
        minutes: 6,
        objective: "Know the name of every open string by sight and sound.",
        learn: [
          { title: "The six strings", body: "From thickest (lowest) to thinnest (highest): E, A, D, G, B, E. The two E strings are two octaves apart." },
          { title: "A memory phrase", body: "'Eddie Ate Dynamite, Good Bye Eddie' — the first letters give you E A D G B E from low to high." },
          { title: "Say them as you pluck", body: "Point to each string and say its name out loud while you play it. Naming while doing locks it in fast." },
        ],
        practice: [
          "Play each string low to high, naming it out loud: E–A–D–G–B–E.",
          "Now high to low: E–B–G–D–A–E.",
          "Close your eyes, pluck a random string, and name it before opening them.",
        ],
        playAlong: "Play all six strings slowly like a gentle wash of sound, naming each. This is your first 'chord' — the open strings ringing together.",
        tip: "The 6th (low E) and 1st (high E) share a name. If you get lost, find the thickest string — that's always low E.",
      },
      {
        id: "m1l5",
        title: "The Classical Right Hand",
        subtitle: "p, i, m, a — your four voices",
        minutes: 10,
        objective: "Name and use the classical right-hand fingers with free strokes and rest strokes.",
        learn: [
          { title: "Four finger names", body: "Classical guitar names the right-hand fingers in Spanish: p (thumb), i (index), m (middle), a (ring). Every fingerstyle pattern in this app uses these letters." },
          { title: "The free stroke", body: "Pluck through the string and let the fingertip follow through into the air. Light and open — this is your everyday stroke for chords and arpeggios." },
          { title: "The rest stroke", body: "Pluck and let the finger come to rest against the next string. It gives a fuller, rounder note — perfect for melodies that need to sing." },
          { title: "Home positions", body: "The thumb (p) covers strings 6, 5 and 4. The fingers live above the treble strings: i on the 3rd, m on the 2nd, a on the 1st." },
        ],
        practice: [
          "Alternate i and m free strokes on the open high E string — 20 even, clean notes.",
          "Play 10 rest strokes with m on the open B string. Hear how much rounder they sound.",
          "Walk the thumb p across strings 6, 5, 4 slowly, keeping the fingers resting lightly on the trebles.",
        ],
        playAlong: "With the Metronome at 60 BPM, alternate i-m on one string, one note per click, for a full minute.",
        tip: "Pluck from the big knuckle, not the fingertip joint, and keep the wrist gently arched — like holding a small orange under your palm.",
      },
      {
        id: "m1l3",
        title: "Fretting a Clean Note",
        subtitle: "Left-hand position that rings clear",
        minutes: 10,
        objective: "Press a fretted note that rings cleanly with no buzz.",
        learn: [
          { title: "Press behind the fret", body: "Place your fingertip just behind the metal fret wire, not on top of it and not in the middle of the space. This gives a clear note with the least effort." },
          { title: "Use your fingertips", body: "Come down on the very tip of the finger so you don't accidentally mute the neighbouring strings." },
          { title: "Thumb behind the neck", body: "Rest your thumb on the back of the neck, roughly opposite your fingers. This gives your fingers leverage to press." },
        ],
        practice: [
          "Press the 3rd fret of the B string with your ring finger and play it. Adjust until it rings with zero buzz.",
          "Lift off, shake out your hand, and place it again. Repeat 10 times aiming for a clean note first try.",
          "Walk one finger up frets 1–2–3–4 on the G string, one clear note each.",
        ],
        playAlong: "Play the melody of the first line of 'Mary Had a Little Lamb' on the B string: 3rd fret, 1st fret, open, 1st fret — slowly and cleanly.",
        tip: "Buzzing usually means you're too far behind the fret or not pressing quite hard enough. Creep your finger toward the fret wire.",
      },
      {
        id: "m1l4",
        title: "Your First Melody",
        subtitle: "Playing on the top strings",
        minutes: 12,
        objective: "Play a simple, recognizable melody one note at a time.",
        scripture: { text: "O sing unto the LORD a new song: sing unto the LORD, all the earth.", ref: "Psalm 96:1" },
        learn: [
          { title: "One note at a time", body: "Melody is single notes played in sequence. Alternate i and m so no finger plays twice in a row." },
          { title: "Count as you go", body: "Say '1, 2, 3, 4' steadily and play a note on each count. Even timing matters more than speed." },
          { title: "Look ahead", body: "Glance at the next note before you finish the current one so your hand is already moving there." },
        ],
        practice: [
          "Play 'Ode to Joy' on the B and high-E strings: B(open)-B-C(1st fret)-D(3rd)... take it four notes at a time.",
          "Play it again counting out loud to keep steady time.",
          "Try the same phrase with rest strokes and hear the melody sing out.",
        ],
        playAlong: "Play the melody slowly along with the Metronome tool at 60 BPM, one note per click.",
        tip: "If a passage trips you up, slow down until you can play it perfectly, then speed up. Speed is a by-product of accuracy.",
      },
      {
        id: "m1l6",
        title: "In Tune, In Tone",
        subtitle: "Your tuning ritual & tone colors",
        minutes: 8,
        objective: "Tune quickly every session and shape your tone by where you pluck.",
        learn: [
          { title: "Tune every time", body: "Open the Tuner tool and match each string, low E to high E, at the start of every session. Nylon strings drift — tuning is a ritual, not a chore." },
          { title: "Three tone colors", body: "Pluck the same string over the soundhole (warm and full), near the fingerboard (soft and dark), and near the bridge (bright and glassy). One guitar, three voices." },
          { title: "Care for the sound", body: "Wipe your strings after playing, and keep your fretting nails short so the fingertips land squarely." },
        ],
        practice: [
          "Tune all six strings with the Tuner tool, saying each string name as you go.",
          "Play the open B string in the three tone positions — soundhole, fingerboard, bridge — and hear the difference.",
          "Play the 'Ode to Joy' phrase from the last lesson in your warmest tone position.",
        ],
        playAlong: "Before anything else today, tune. Then play any melody you know in each of the three tone colors.",
        tip: "An in-tune guitar makes everything you play sound twice as good. It's the cheapest upgrade there is.",
      },
    ],
  },
  {
    id: "m2",
    num: 2,
    title: "Rhythm & Strumming",
    subtitle: "Keeping time & worship strum patterns",
    lessons: [
      {
        id: "m2l1",
        title: "Feeling the Beat",
        subtitle: "Counting in 4/4 time",
        minutes: 8,
        objective: "Feel and count a steady 4/4 pulse — the backbone of worship music.",
        learn: [
          { title: "Four beats to a bar", body: "Most worship songs are in 4/4: you count '1, 2, 3, 4' over and over. Beat 1 feels the strongest." },
          { title: "Tap it out", body: "Tap your foot on every number. The foot is your inner clock — keep it going no matter what your hands do." },
          { title: "Subdivide", body: "Between each number is an 'and': 1-and-2-and-3-and-4-and. Those 'ands' are where up-strums live." },
        ],
        practice: [
          "Tap your foot and count '1 2 3 4' out loud for one minute with the metronome at 70 BPM.",
          "Now count the 'ands': 1-and-2-and-3-and-4-and, still tapping only on the numbers.",
        ],
        playAlong: "Open the Metronome tool at 70 BPM and count along until it feels automatic.",
        tip: "If your strumming ever falls apart, it's almost always the foot that stopped. Keep it moving.",
      },
      {
        id: "m2l2",
        title: "The Down Strum",
        subtitle: "Even quarter-note strums",
        minutes: 10,
        objective: "Strum steady down-strokes in time on one chord.",
        chords: ["Em"],
        learn: [
          { title: "Brush, don't hit", body: "Strum from the wrist, brushing down across the strings. Let the thumb or pick glide — you're painting, not chopping." },
          { title: "One strum per beat", body: "Play a down-strum on each count: 1, 2, 3, 4. This is 'quarter-note' strumming." },
          { title: "Keep the arm moving", body: "Your strumming hand keeps a steady down-motion even between strums, like a pendulum." },
        ],
        practice: [
          "Hold an E minor chord and strum down on every beat at 70 BPM for two minutes.",
          "Count out loud while you strum: 'down-2-3-4' every bar.",
        ],
        playAlong: "Set the Progression Looper to any key and use just the click — strum a down-stroke on each beat.",
        tip: "Aim your strum at the middle of the strings, not the edges, for the fullest sound.",
      },
      {
        id: "m2l3",
        title: "Down-Up Patterns",
        subtitle: "Adding upstrokes for movement",
        minutes: 12,
        objective: "Add up-strums on the 'and' to create flow and momentum.",
        chords: ["G"],
        learn: [
          { title: "The up-strum", body: "On the way back up, catch just the top 2–3 strings. Up-strums are lighter than down-strums." },
          { title: "Down on numbers, up on ands", body: "Down = 1 2 3 4, Up = the 'ands' in between. Try: down-up-down-up all bar (eighth notes)." },
          { title: "Let some strums miss", body: "You don't have to hit strings on every motion. The hand keeps moving; you choose when to make contact." },
        ],
        practice: [
          "On a G chord, strum steady eighths: D-U-D-U-D-U-D-U at 70 BPM.",
          "Try the pattern D-D-U-U-D-U and repeat it around the bar.",
        ],
        playAlong: "Loop a 1-5-6-4 progression at a slow tempo and lay your down-up pattern over it.",
        tip: "Keep your wrist loose. A stiff arm makes up-strums clunky — the motion should feel like shaking water off your hand.",
      },
      {
        id: "m2l4",
        title: "The Worship Strum",
        subtitle: "A gentle pattern for ballads",
        minutes: 12,
        objective: "Play the most common flowing worship strum pattern.",
        scripture: { text: "Sing unto him a new song; play skilfully with a loud noise.", ref: "Psalm 33:3" },
        chords: ["C"],
        learn: [
          { title: "The pattern", body: "The classic worship strum is: Down, Down-Up, Up-Down-Up — counted 1, 2-and, and-3-and (with a miss on beat 3's down). It flows rather than marches." },
          { title: "Ghost the misses", body: "Keep your hand moving through the strums you skip so the rhythm stays even." },
          { title: "Dynamics", body: "Play softer in verses, fuller in choruses. The same pattern can whisper or soar." },
        ],
        practice: [
          "On a C chord, play D · D-U · U-D-U slowly until it's smooth.",
          "Speed it up gradually to 75 BPM, keeping it relaxed and flowing.",
        ],
        playAlong: "Loop a 1-5-6-4 progression at 72 BPM and play the worship strum through the chord changes.",
        tip: "This one pattern fits a huge portion of modern worship songs. Master it and you can play along with almost anything.",
      },
      {
        id: "m2l5",
        title: "Waltz Time",
        subtitle: "Playing hymns in 3/4",
        minutes: 10,
        objective: "Play confidently in 3/4 — the time signature of many beloved hymns.",
        scripture: { text: "And when they had sung an hymn, they went out into the mount of Olives.", ref: "Matthew 26:30" },
        chords: ["G", "C", "D"],
        learn: [
          { title: "Three beats to a bar", body: "In 3/4 you count '1, 2, 3' — one strong beat, two light ones. It sways like a waltz instead of marching like 4/4." },
          { title: "Bass, strum, strum", body: "On beat 1, pluck just the bass note of the chord with your thumb. On beats 2 and 3, strum the rest. This is the classic hymn accompaniment." },
          { title: "Let it lilt", body: "Don't force it — 3/4 should feel like a gentle rocking. Lean into beat 1 and let 2 and 3 float." },
        ],
        practice: [
          "On G, play bass-strum-strum at 72 BPM for one minute. The bass note is the low E string, 3rd fret.",
          "Move through G, C and D, one bar each, keeping the bass-strum-strum pattern.",
          "Count '1-2-3' out loud the whole time — the count is the skill.",
        ],
        playAlong: "Open 'Amazing Grace' in the Song Library — it's in 3/4 — and play along with the chart.",
        tip: "Amazing Grace, Be Thou My Vision, Blessed Assurance — many of the church's most-loved songs live in 3/4. This pattern unlocks them all.",
      },
      {
        id: "m2l6",
        title: "Fingerstyle Foundations",
        subtitle: "p-i-m-a arpeggio patterns",
        minutes: 12,
        objective: "Play a steady fingerpicked arpeggio pattern through a chord.",
        scripture: { text: "Sing unto the LORD with the harp; with the harp, and the voice of a psalm.", ref: "Psalm 98:5" },
        chords: ["Em"],
        learn: [
          { title: "Plant the hand", body: "Hold E minor. Place p on the low E string, i on the G, m on the B, a on the high E. This 'planted' start keeps the hand quiet and accurate." },
          { title: "Ripple upward", body: "Play p, then i, then m, then a — four even free strokes, low to high. Let every note ring into the next." },
          { title: "Come back down", body: "Extend the pattern to p-i-m-a-m-i for a six-note ripple that rises and falls. This is the heartbeat of countless worship ballads." },
        ],
        practice: [
          "On Em, play p-i-m-a slowly and evenly at 60 BPM, one note per click, for two minutes.",
          "Switch to p-i-m-a-m-i, one full pattern per bar.",
          "Keep your fingertips close to the strings between notes — small motions, warm tone.",
        ],
        playAlong: "Loop a slow 1-5-6-4 and fingerpick p-i-m-a through each chord instead of strumming.",
        tip: "Fingerstyle is where the classical guitar shines in worship — intimate verses, gentle communion moments, spontaneous worship. This pattern will serve you for years.",
      },
      {
        id: "m2l7",
        title: "The Modern Ballad",
        subtitle: "Staying steady when it's slow",
        minutes: 12,
        objective: "Hold a slow modern worship tempo (64–72 BPM) steady and full without rushing.",
        scripture: { text: "And he hath put a new song in my mouth, even praise unto our God: many shall see it, and fear, and shall trust in the LORD.", ref: "Psalm 40:3" },
        chords: ["G", "Cadd9", "Em7", "Dsus4"],
        learn: [
          { title: "Slow is the hard part", body: "Modern worship ballads sit around 66–72 BPM — far slower than most hymns. The space between beats is where beginners rush. The fix is subdividing: count '1-e-and-a, 2-e-and-a' so every beat is full of silent structure." },
          { title: "Driving eighths", body: "The modern ballad engine is constant down-up eighth strums, played softly. The motion never changes — only your dynamics swell and recede. It should feel like slow breathing, not marching." },
          { title: "Let the colors ring", body: "Play the loop with Cadd9 and Em7 instead of C and Em, keeping your ring and pinky anchored where shapes share notes. Those ringing common tones are the signature modern worship sound." },
          { title: "Grow without speeding", body: "The number-one ballad mistake: getting louder also gets faster. Practice swelling from a whisper to full and back while the click proves your tempo never moved." },
        ],
        practice: [
          "Metronome at 68 BPM: count '1-e-and-a' out loud for one minute, clapping only the beats.",
          "On Cadd9, play soft driving eighths at 68 BPM for two minutes without a single rush.",
          "Loop G – Dsus4 – Em7 – Cadd9 at 66 BPM, one bar each, swelling louder each pass then back down.",
          "Record 30 seconds on your phone and listen: did the tempo creep when you got louder?",
        ],
        playAlong: "Open Practice Tracks and play 'Still Waters' at 66 BPM — hold driving eighths against the pad and drums. The track is your accountability.",
        tip: "If you can stay steady at 66 BPM, every faster song feels easy. Slow tempo control is the most underrated skill on a worship team.",
      },
      {
        id: "m2l8",
        title: "Pushes & Syncopation",
        subtitle: "The modern rhythmic accent",
        minutes: 13,
        objective: "Anticipate chord changes on the 'and' — the push that makes modern worship move.",
        chords: ["G", "C", "D", "Em"],
        learn: [
          { title: "What a push is", body: "Instead of changing chords exactly on beat 1, modern songs often hit the new chord half a beat early — on the 'and of 4'. That anticipation is called a push, and it's everywhere in contemporary worship." },
          { title: "How to play one", body: "Start moving your fretting hand during beat 4, catch the new chord with an up-strum on the 'and', then let it ring through beat 1. The up-strum IS the arrival." },
          { title: "Percussive chucks", body: "Relax your fretting fingers to mute the strings and strum a dead 'chuck' on beats 2 and 4. Mixed with pushes, this turns one guitar into a rhythm section." },
          { title: "Fast anthems simplify", body: "Upbeat openers run at 120–140 BPM. At those speeds, do less: solid down-strums on the beats, and save pushes for section changes. Energy comes from the tempo, not from busy hands." },
        ],
        practice: [
          "Loop G to C at 72 BPM, pushing every change on the 'and of 4'. Ten clean pushed changes.",
          "Add a muted chuck on beats 2 and 4 while strumming G — one minute, steady.",
          "Anthem drill: set the Metronome to 126 BPM and play straight down-strums through 1-5-6-4, clean and relaxed.",
          "Alternate one pass pushed and one pass on the beat, and hear how the push changes the song's energy.",
        ],
        playAlong: "Open Practice Tracks: push every change on 'Ever Faithful' at 84 BPM, then switch to 'Risen King' at 126 and simplify to down-strums.",
        tip: "Count pushes out loud ('4-AND') until they're automatic. A push you have to think about lands late — a felt push lands early, which is the whole point.",
      },
    ],
  },
  {
    id: "m3",
    num: 3,
    title: "Chord Shapes",
    subtitle: "Open chords, color chords, barre chords & the capo",
    lessons: [
      {
        id: "m3l1",
        title: "Reading Chord Charts",
        subtitle: "Dots, fingers, and open strings",
        minutes: 7,
        objective: "Read a chord diagram fluently so you can learn any new shape.",
        chords: ["Em"],
        learn: [
          { title: "The grid", body: "Vertical lines are strings (low E on the left), horizontal lines are frets. The thick bar at the top is the nut." },
          { title: "Dots and numbers", body: "A dot shows where to press; the number inside tells you which finger (1=index, 2=middle, 3=ring, 4=pinky)." },
          { title: "Above the nut", body: "An 'o' means play that string open; an 'x' means don't play it at all." },
        ],
        practice: [
          "Read the E minor diagram and place your fingers from it without help.",
          "Play the chord one string at a time to check every note rings — fix any that buzz or are muted.",
        ],
        playAlong: "Strum E minor slowly with the worship strum from Module 2.",
        tip: "Whenever you meet a new chord in this app, the diagram tells you everything. Learn to read it and you're self-sufficient.",
      },
      {
        id: "m3l2",
        title: "The E Minor Chord",
        subtitle: "Your first full chord",
        minutes: 8,
        objective: "Play a clean, full-sounding E minor — the easiest chord on guitar.",
        chords: ["Em"],
        learn: [
          { title: "Two fingers", body: "Middle finger on the A string (5th), 2nd fret. Ring finger on the D string (4th), 2nd fret. Everything else rings open." },
          { title: "Strum all six", body: "E minor uses all six strings, so strum from the low E straight through." },
          { title: "Listen for ring", body: "Both open E strings and the open G and B should ring clearly alongside your two fretted notes." },
        ],
        practice: [
          "Form E minor, strum, and check each string rings.",
          "Lift off, shake out, and re-form it 10 times, aiming for a clean chord first try.",
        ],
        playAlong: "Strum E minor with the worship strum for a full minute — let it become effortless.",
        tip: "E minor is the 6th chord in the key of G and the 6 in a 1-5-6-4 — you'll use it constantly.",
      },
      {
        id: "m3l3",
        title: "The G Major Chord",
        subtitle: "The most-used chord in worship music",
        minutes: 10,
        objective: "Play a clean G major and know why it matters.",
        chords: ["G"],
        learn: [
          { title: "Place your fingers", body: "Middle finger on the low E (6th), 3rd fret. Index on the A (5th), 2nd fret. Ring finger on the high E (1st), 3rd fret." },
          { title: "Let the middle strings ring", body: "The D, G, and B strings stay open. Arch your fingers so they don't touch them." },
          { title: "Strum all six", body: "G is a full six-string chord — big and joyful." },
        ],
        practice: [
          "Form G, strum, and check every string is clear.",
          "Practice landing all three fingers at once, not one at a time.",
        ],
        playAlong: "Alternate two bars of G and two bars of E minor with the worship strum.",
        tip: "G is the '1' (home chord) of the most common worship key. If you learn one chord well, make it this one.",
      },
      {
        id: "m3l4",
        title: "The C & D Chords",
        subtitle: "Completing the key of G",
        minutes: 10,
        objective: "Add C major and D major so you can play in the key of G.",
        chords: ["C", "D"],
        learn: [
          { title: "C major", body: "Ring finger on the A (5th) 3rd fret, middle on the D (4th) 2nd fret, index on the B (2nd) 1st fret. Don't play the low E." },
          { title: "D major", body: "A small triangle on the top strings: index on G (3rd) 2nd fret, ring on B (2nd) 3rd fret, middle on high E (1st) 2nd fret. Play from the D string down." },
          { title: "Now you have four", body: "G, C, D, and Em together give you the four chords behind thousands of worship songs." },
        ],
        practice: [
          "Form C, check it rings, then D, then back. Go slowly.",
          "Play one bar each: G – C – D – Em, resetting as needed.",
        ],
        playAlong: "Loop a 1-4-6-5 progression in G (G-C-Em-D) and strum along at a slow tempo.",
        tip: "For C and D, avoid strumming the low E string — start your strum from the A or D string.",
      },
      {
        id: "m3l8",
        title: "A Minor & D Minor",
        subtitle: "The reflective colors",
        minutes: 10,
        objective: "Play the two open minor chords that give worship its tender moments.",
        scripture: { text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.", ref: "Psalm 34:18" },
        chords: ["Am", "Dm"],
        learn: [
          { title: "A minor", body: "Middle finger on the D (4th) 2nd fret, ring on the G (3rd) 2nd fret, index on the B (2nd) 1st fret. Skip the low E. It's the E-major hand shape moved over one string set." },
          { title: "D minor", body: "Middle on the G (3rd) 2nd fret, ring on the B (2nd) 3rd fret, index on the high E (1st) 1st fret. Play from the D string down." },
          { title: "Hear the difference", body: "Play D major, then D minor. That one note lower — the third — is the difference between bright and sorrowful. Minor chords carry lament, longing and reverence." },
        ],
        practice: [
          "Alternate A minor and E major — notice it's the same finger shape shifted across. 10 clean swaps.",
          "Alternate D major and D minor slowly, listening to the color change.",
          "Play one bar each: Am – Dm – G – C, with the worship strum.",
        ],
        playAlong: "Loop a 6-4-1-5 progression in C (Am-F-C-G becomes Am-C-G if you skip F for now) — or simply alternate Am and Dm with a gentle fingerpicked pattern.",
        tip: "The Psalms have laments as well as praises. Minor chords let your guitar pray both.",
      },
      {
        id: "m3l9",
        title: "E & A Major",
        subtitle: "Completing the open majors",
        minutes: 10,
        objective: "Add E major and A major — the bright keys of celebration.",
        chords: ["E", "A"],
        learn: [
          { title: "E major", body: "Middle on the A (5th) 2nd fret, ring on the D (4th) 2nd fret, index on the G (3rd) 1st fret. All six strings ring — the biggest chord on the guitar." },
          { title: "A major", body: "Fingers 1, 2, 3 side by side on the 2nd fret of the D, G and B strings. Skip the low E, let the open A be the bass." },
          { title: "Why they matter", body: "E and A open up the keys of E, A and D — bright, congregational keys you'll meet constantly on a worship team." },
        ],
        practice: [
          "Form E major, strum all six, check for buzzes. Then A major, strumming from the 5th string.",
          "Change E to A and back, 10 clean swaps at your own pace.",
          "Play one bar each of A – D – E and repeat — the classic 1-4-5 in the key of A.",
        ],
        playAlong: "Loop a 1-5-6-4 progression in the key of A and strum through it: A – E – F#m appears later, so for now just play the A, D and E bars strongly.",
        tip: "E major and E minor differ by one finger. A major and A minor differ by one note. Learn the pairs together and you double your vocabulary for free.",
      },
      {
        id: "m3l10",
        title: "Color Chords",
        subtitle: "sus, add9 & slash chords",
        minutes: 12,
        objective: "Add the modern worship colors: sus4, add9, minor 7 and slash chords.",
        chords: ["Dsus4", "Asus4", "Cadd9", "Em7", "G/B"],
        learn: [
          { title: "Suspended chords", body: "A sus4 replaces the chord's third with the fourth — it sounds unresolved, like a held breath. Play D, add your pinky on the high E 3rd fret for Dsus4, then lift it: tension, release." },
          { title: "The add9 shimmer", body: "Cadd9 is a C chord with an extra color note. Swap it in wherever a song asks for C and hear the modern worship shimmer." },
          { title: "Minor 7 warmth", body: "Em7 softens E minor by adding a gentle seventh — your pinky on the B string, 3rd fret. It blends beautifully under vocals." },
          { title: "Slash chords walk the bass", body: "G/B means 'a G chord with B in the bass'. Use it to walk smoothly between C and Am: C → G/B → Am, the bass stepping down one note at a time." },
        ],
        practice: [
          "Play D → Dsus4 → D, moving only the pinky, at 70 BPM. This is one of the most-used moves in worship guitar.",
          "Do the same with A → Asus4 → A.",
          "Play the descending walk C → G/B → Am slowly, listening to the bass line step down.",
          "Play a 1-5-6-4 in G substituting Cadd9 for C and Em7 for Em.",
        ],
        playAlong: "Loop 1-5-6-4 in G and decorate it: sus the D chord, shimmer the C. Hear how color chords keep a simple loop interesting.",
        tip: "Color chords are seasoning, not the meal. Use them where the song breathes — too many and the harmony loses its shape.",
        theory: "A chord is built from its 1st, 3rd and 5th scale notes. 'Sus' chords suspend the 3rd (replacing it with the 4th), 'add9' stacks the 9th (the 2nd, an octave up) on top, and a slash chord like G/B keeps the same notes but changes which one is lowest.",
      },
      {
        id: "m3l5",
        title: "Smooth Transitions",
        subtitle: "Changing chords without stopping",
        minutes: 10,
        objective: "Move between chords in time without pausing the strum.",
        chords: ["G", "C", "D", "Em"],
        learn: [
          { title: "Look for common fingers", body: "Between some chords a finger stays put or barely moves. Find those 'anchor' fingers and pivot around them." },
          { title: "Move as a shape", body: "Lift and place all fingers together as one unit, not one at a time." },
          { title: "Change on the last up-strum", body: "Start moving to the next chord slightly early, during the final up-strum of the bar, so you land on beat 1." },
        ],
        practice: [
          "Change G to C over and over, just the hands, no strumming, aiming for a clean landing.",
          "Now add one strum per chord, changing every beat. Keep the metronome slow.",
          "Run the full circuit G – C – D – Em – G until it loops without hesitation.",
        ],
        playAlong: "Loop G-C-D-G at a very slow tempo and change chords in time with the click.",
        tip: "It's better to change on time with a slightly rough chord than to stop and 'fix' it. Keep the beat and the fingers will catch up.",
      },
      {
        id: "m3l11",
        title: "The Barre Chord",
        subtitle: "F major and B minor",
        minutes: 14,
        objective: "Play your first barre chords — the gateway to every key.",
        scripture: { text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not.", ref: "Galatians 6:9" },
        chords: ["F", "Bm"],
        learn: [
          { title: "The barre itself", body: "Lay your index finger flat across all six strings at the 1st fret, rolled slightly onto its bony edge. Squeeze gently with the thumb behind the neck — pressure comes from the arm pulling back, not the thumb crushing." },
          { title: "Build the F", body: "Keep the barre, then add: middle on the G (3rd) 2nd fret, ring on the A (5th) 3rd fret, pinky on the D (4th) 3rd fret. That's the E-major shape behind a barre." },
          { title: "B minor", body: "Barre strings 1 through 5 at the 2nd fret, then add the A-minor shape: middle on the B (2nd) 3rd fret, ring on the D (4th) 4th fret, pinky on the G (3rd) 4th fret." },
          { title: "Be patient", body: "Every guitarist finds barre chords hard at first — it's strength you simply haven't built yet. Short, frequent attempts beat long painful sessions." },
        ],
        practice: [
          "Barre the 1st fret alone and strum. Listen for which strings buzz, adjust, repeat. 5 attempts.",
          "Form the full F and hold it for 20 seconds, strumming once. Rest. Repeat 3 times.",
          "Play B minor one string at a time, fixing dead notes as you find them.",
          "Change G → Bm → C slowly — Bm is the '3' chord you've been missing in the key of G.",
        ],
        playAlong: "Try 'What a Beautiful Name' in the Song Library — its D-A-Bm-G loop is the perfect Bm workout.",
        tip: "If the full barre defeats you today, play the small F (just the top four strings) and keep moving. Strength arrives with days, not hours.",
        theory: "A barre chord is a movable nut: the E-major shape barred at the 1st fret is F, at the 3rd it's G, at the 5th it's A. Learn one shape and the low-E string's note names hand you a dozen chords.",
      },
      {
        id: "m3l6",
        title: "Using a Capo",
        subtitle: "Play easy shapes in any key",
        minutes: 8,
        objective: "Use a capo to match a singer's key while keeping easy open shapes.",
        learn: [
          { title: "What a capo does", body: "A capo clamps across a fret and raises the pitch of every string. Your open shapes now sound higher, in a new key." },
          { title: "Place it well", body: "Clamp just behind the fret (like a good fretting finger) so nothing buzzes. Check each string rings." },
          { title: "Find the fret", body: "Use the Capo & Keys tool: tell it the key you need, and it shows which shapes to play and where to clamp." },
        ],
        practice: [
          "Put a capo on the 2nd fret and play your G shape — it now sounds as A. Play G-C-D shapes and hear the new key.",
          "Use the Capo & Keys tool to find the capo for the key of Bb, then play it.",
        ],
        playAlong: "Capo 2, then loop G-C-D-Em shapes — you're now playing in the key of A.",
        tip: "Capos are standard on worship teams. Two guitarists often capo differently to layer the same song richly.",
      },
      {
        id: "m3l7",
        title: "Your First Worship Song",
        subtitle: "Putting it all together",
        minutes: 12,
        objective: "Play a full, simple worship song start to finish.",
        scripture: { text: "Serve the LORD with gladness: come before his presence with singing.", ref: "Psalm 100:2" },
        chords: ["G", "D", "Em", "C"],
        progression: { key: "G", degrees: [1, 5, 6, 4] },
        learn: [
          { title: "The progression", body: "Many worship songs are just 1-5-6-4. In G that's G-D-Em-C, looping through verse and chorus." },
          { title: "Steady over perfect", body: "Keep the worship strum going and change chords in time. A steady groove carries the song." },
          { title: "Build dynamics", body: "Play the verse softly, then strum fuller in the chorus to lift the room." },
        ],
        practice: [
          "Loop G-D-Em-C with the worship strum, two strums to a bar, at 72 BPM.",
          "Play it four times through without stopping, even if a chord is rough.",
        ],
        playAlong: "Use the Progression Looper in G, 1-5-6-4, and play the full pattern along with it.",
        tip: "Congratulations — this four-chord loop is a real worship song engine. Head to the Song Library to try it on actual songs.",
      },
    ],
  },
  {
    id: "m4",
    num: 4,
    title: "Lead & Melody",
    subtitle: "Scales, melody & expressive lead playing",
    lessons: [
      {
        id: "m4l1",
        title: "The Major Scale",
        subtitle: "The roadmap of melody",
        minutes: 14,
        objective: "Play the G major scale cleanly in open position and understand how it's built.",
        scripture: { text: "For God is King of all the earth: sing ye praises with understanding.", ref: "Psalm 47:7" },
        learn: [
          { title: "The formula", body: "Every major scale follows the same step pattern: whole-whole-half-whole-whole-whole-half. On guitar a whole step is two frets, a half step is one." },
          { title: "One octave in G", body: "Start on the low E string, 3rd fret (G). Then: A (5th string open), B (5th, 2nd fret), C (5th, 3rd), D (4th open), E (4th, 2nd), F# (4th, 4th), G (3rd open). Eight notes, one octave." },
          { title: "One finger per fret", body: "In open position, match fingers to frets: index for the 1st fret, middle for the 2nd, ring for the 3rd, pinky for the 4th. Your hand stays still; only the fingers move." },
          { title: "Alternate i and m", body: "Pluck the scale with alternating index and middle free strokes. Never let the same finger play twice in a row." },
          { title: "Sing what you play", body: "Sing or hum each note as you play it — do, re, mi. Connecting ear to fingers is what turns a scale into music." },
        ],
        practice: [
          "Play the G major scale ascending and descending, one note per click at 60 BPM, five clean passes.",
          "Play it again with your eyes closed, feeling the string changes.",
          "Say the note names out loud as you play: G, A, B, C, D, E, F-sharp, G.",
        ],
        playAlong: "Loop a G chord in the Progression Looper and play the scale over it — hear how every note belongs to the key.",
        tip: "Slow and perfectly even beats fast and lumpy every time. The metronome is your best teacher this month.",
        theory: "The key of G major has exactly one sharp — F# — which is why the scale needs the 4th fret on the D string. Every major key uses the same whole/half-step formula starting from a different note; the sharps and flats exist to preserve that spacing.",
      },
      {
        id: "m4l5",
        title: "Knowing the Fretboard",
        subtitle: "Finding notes by name",
        minutes: 12,
        objective: "Name and find notes across the neck using landmarks and octave shapes.",
        learn: [
          { title: "Twelve then repeat", body: "After twelve frets the notes start over: the 12th fret of any string is the same note as the open string, an octave higher." },
          { title: "Landmarks on the low E", body: "Learn five anchors: 3rd fret G, 5th fret A, 7th fret B, 8th fret C, 10th fret D. With the open E and the 12th-fret E, you can now name the whole string." },
          { title: "Landmarks on the A string", body: "Same trick: 3rd fret C, 5th fret D, 7th fret E, 8th fret F, 10th fret G. These two strings name every barre chord you'll ever play." },
          { title: "The octave shape", body: "From any note on the 6th or 5th string, the same note lives two strings higher and two frets up. Play the low G (6th string, 3rd fret) and its octave (4th string, 5th fret) together." },
        ],
        practice: [
          "Name every note on the low E string from open to the 12th fret, then check yourself against the landmarks.",
          "Find all the G notes you can in the first five frets — there are three (6th string 3rd fret, 3rd string open, 1st string 3rd fret).",
          "Pick a random letter name each day and find it on strings 6 and 5 within five seconds.",
        ],
        playAlong: "Play the octave shape up the neck along the low E string landmarks: G, A, B, C, D — you're playing a melody in octaves, a classic lead sound.",
        tip: "You don't memorize a fretboard in a day — you memorize five landmarks and let the octave shapes fill in the rest.",
        theory: "Guitar strings are tuned in perfect fourths except between the G and B strings, which is a major third. That one irregularity is why octave and chord shapes shift up one fret whenever they cross the B string.",
      },
      {
        id: "m4l2",
        title: "Playing a Hymn Melody",
        subtitle: "Be Thou My Vision, one note at a time",
        minutes: 15,
        objective: "Play a recognizable hymn melody as a singing lead line.",
        scripture: { text: "Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord.", ref: "Ephesians 5:19" },
        learn: [
          { title: "Melody is scale notes", body: "A hymn tune is the major scale rearranged into a beautiful order. You already have every note under your fingers from the last lessons." },
          { title: "Phrase by phrase", body: "Learn the first line, then the second, then join them. A hymn is four singable phrases — treat each one like a sentence." },
          { title: "Let it breathe", body: "Leave small spaces between phrases like a singer taking a breath. Music lives in the gaps too." },
          { title: "Rest strokes for the tune", body: "Play the melody with rest strokes — each note lands on the neighbouring string with a full, round tone that carries over accompaniment." },
          { title: "Trust your ear", body: "You know this tune. When a note sounds wrong, it is wrong — hunt one fret up or down until your ear says yes." },
        ],
        practice: [
          "Learn the first phrase of 'Be Thou My Vision' by ear on the top three strings, slowly.",
          "Add the second phrase and play them joined, breathing between them.",
          "Play the full first verse melody at 60 BPM with rest strokes.",
          "Record yourself on your phone and listen back — does the melody sing?",
        ],
        playAlong: "Open 'Be Thou My Vision' in the Song Library, and play the melody while the chart's chords play underneath.",
        tip: "Playing familiar melodies is the fastest ear training there is — you already know when a note is wrong.",
        theory: "Hymn tunes move mostly by step (neighbouring scale notes) because congregations sing them — this is called conjunct motion. When a hymn does leap, it usually outlines the underlying chord, which is why melody and harmony feel inseparable.",
      },
      {
        id: "m4l3",
        title: "The Pentatonic Scale",
        subtitle: "Five notes for lead lines",
        minutes: 14,
        objective: "Play the open-position E minor pentatonic and use it for simple lead lines.",
        learn: [
          { title: "Five friendly notes", body: "The pentatonic scale drops two notes from the seven-note scale, removing the half-step tensions. What's left — E, G, A, B, D — sounds good over almost everything in the key." },
          { title: "The open shape", body: "Every string, open plus one fretted note: 6th string open then 3rd fret; 5th open then 2nd; 4th open then 2nd; 3rd open then 2nd; 2nd open then 3rd; 1st open then 3rd." },
          { title: "Up and down evenly", body: "Climb from low E to high G and back, alternating i and m, letting each note ring its full length." },
          { title: "Target chord tones", body: "When improvising, aim to land on notes that are in the current chord — over Em land on E, G or B; over C land on C, E or G. Landing notes make lines sound intentional." },
        ],
        practice: [
          "Play the open Em pentatonic up and down, two notes per beat at 70 BPM, five passes.",
          "Improvise four notes from the scale, then rest for four beats. Repeat, changing your four notes each time.",
          "Over an Em chord in the Looper, practice ending every little phrase on E, G or B.",
        ],
        playAlong: "Loop a 6-4-1-5 progression in G and improvise using only the pentatonic shape — every note will fit.",
        tip: "You don't need many notes to sound good in worship — a few well-placed pentatonic notes say more than a flurry.",
        theory: "E minor pentatonic contains the same five notes as G major pentatonic — E is the relative minor of G. That's why this one shape works over the whole key of G: you're always playing notes the key already owns.",
      },
      {
        id: "m4l6",
        title: "Hammer-Ons & Pull-Offs",
        subtitle: "Slurs that make lines sing",
        minutes: 13,
        objective: "Connect notes with left-hand slurs for smooth, vocal-sounding lines.",
        learn: [
          { title: "The hammer-on", body: "Pluck the open G string, then snap your middle finger down onto the 2nd fret without plucking again. Two notes, one stroke — the second born entirely from the left hand." },
          { title: "The pull-off", body: "Reverse it: fret the 2nd fret, pluck, then flick the finger slightly downward as it lifts so the open string sounds. The flick is the pluck." },
          { title: "From the knuckle", body: "Classical players call slurs ligados. Power comes from the big knuckle moving decisively — precision, not violence. The slurred note should match the plucked note's volume." },
          { title: "Combine them", body: "Pluck-hammer-pull (0h2p0) makes three notes from one stroke — the ornament behind countless worship intro licks." },
        ],
        practice: [
          "On each of the top three strings: pluck open, hammer the 2nd fret. 10 even pairs per string.",
          "Reverse: fret the 2nd fret, pluck, pull off to open. 10 pairs per string, matching volumes.",
          "Play the Em pentatonic adding one hammer-on per string on the way up and one pull-off per string on the way down.",
        ],
        playAlong: "Loop a slow 1-5-6-4 in G and decorate your pentatonic phrases with one slur per phrase — no more.",
        tip: "If the slurred note is quiet, the finger is arriving lazily. Strike the fret like you mean it — then relax instantly.",
        theory: "Slurs are articulation, not just technique: only the first note is attacked, so the pair sounds connected the way a singer joins two syllables on one breath. Alternating slurred and plucked notes is what gives a lead line its phrasing and shape.",
      },
      {
        id: "m4l7",
        title: "Thirds & Sixths",
        subtitle: "Harmonized melody lines",
        minutes: 14,
        objective: "Harmonize a melody in parallel thirds and sixths — the classical worship sound.",
        learn: [
          { title: "What a third is", body: "Play the open G string and open B string together — that's a third: two scale notes with one skipped between them. Melodies harmonized in thirds instantly sound sweet and vocal." },
          { title: "Climb in thirds", body: "On the G and B strings, play these pairs in the key of G: open+open (G+B), 2nd fret+1st fret (A+C), 4th+3rd (B+D), 5th+5th (C+E). Two-finger chords walking up the scale." },
          { title: "Sixths for warmth", body: "Skip a string for sixths: fret the G string 4th fret (B) with the high E 3rd fret (G) — wider, warmer, glowing. Move both up the scale for the next pair (C with A: 5th fret and 5th fret)." },
          { title: "Use them in songs", body: "Harmonized lines shine in intros, turnarounds and instrumental verses — one guitar sounding like two singers." },
        ],
        practice: [
          "Play the four third-pairs up and back at 60 BPM until the shifts are silent.",
          "Play the two sixth-pairs, then find the next pair up the scale by ear.",
          "Harmonize the first phrase of 'Ode to Joy' in thirds on the G and B strings.",
        ],
        playAlong: "Loop 1-5-6-4 in G and play slow climbing thirds over it as an intro line — instant worship-intro sound.",
        tip: "Thirds and sixths are the same interval flipped upside down. Master one and you already half-know the other.",
        theory: "In a major key, stacking a scale in thirds is where chords come from — a triad is just two thirds piled up. When you harmonize a melody in thirds you're really playing two-note chords that follow the tune, which is why it blends so effortlessly with the underlying harmony.",
      },
      {
        id: "m4l8",
        title: "Arpeggios as Lead Lines",
        subtitle: "Outlining the chords",
        minutes: 15,
        objective: "Build lead lines from chord tones so your playing follows the harmony.",
        chords: ["C", "Am", "F", "G"],
        progression: { key: "C", degrees: [1, 6, 4, 5] },
        learn: [
          { title: "Arpeggio, redefined", body: "You've fingerpicked arpeggios as accompaniment. As lead, an arpeggio means choosing the chord's own notes — root, third, fifth — anywhere on the neck and playing them as melody." },
          { title: "Spell each chord", body: "Over C play C-E-G; over Am play A-C-E; over F play F-A-C; over G play G-B-D. Two chords apart share notes — find the shared ones." },
          { title: "Target the third", body: "The third is each chord's most colorful note — it's what makes it major or minor. Landing on the third at each chord change outlines the harmony most strongly." },
          { title: "Connect by nearest note", body: "Move to the closest chord tone of the next chord rather than jumping to its root. Small moves make elegant lines — this is voice-leading, the heart of classical melody." },
        ],
        practice: [
          "Loop 1-6-4-5 in C and play only chord tones, one note per beat.",
          "Now land on each chord's third on beat 1: E over C, C over Am, A over F, B over G.",
          "Add one passing note between chord tones on the weak beats.",
          "Play the whole loop moving by nearest-note only — never jumping more than two frets.",
        ],
        playAlong: "Use the Progression Looper on 1-6-4-5 in C at 65 BPM and build a one-bar arpeggio phrase per chord.",
        tip: "When the congregation hears your line 'agree' with the chords, it feels like worship. When it fights them, it feels like a solo. Chord tones are how you agree.",
        theory: "Chord tones are the harmonic skeleton: they sound stable at any moment their chord is playing. Non-chord tones (passing and neighbour notes) create motion but want to resolve back to the skeleton — strong beats favor chord tones, weak beats carry the passing notes.",
      },
      {
        id: "m4l4",
        title: "Phrasing & Improvisation",
        subtitle: "Say something, then breathe",
        minutes: 16,
        objective: "Improvise melodic, tasteful lead lines with intentional phrasing.",
        scripture: { text: "And it came to pass, when the evil spirit from God was upon Saul, that David took an harp, and played with his hand: so Saul was refreshed, and was well, and the evil spirit departed from him.", ref: "1 Samuel 16:23" },
        progression: { key: "G", degrees: [1, 5, 6, 4] },
        learn: [
          { title: "Play like you speak", body: "Good improvising is like conversation: short phrases, with space to breathe between them. Don't fill every beat." },
          { title: "Question and answer", body: "Play a short phrase that ends away from the home note — a question. Answer it with a phrase that lands home. Two phrases, one thought." },
          { title: "Repeat and vary", body: "Play a little phrase, then play it again slightly changed. Repetition is what makes a line feel like a melody instead of wandering." },
          { title: "Serve the song", body: "In worship, lead guitar supports the moment — swell into choruses, lay out entirely in quiet verses. The most spiritual note you can play is sometimes none." },
          { title: "End on a chord tone", body: "However adventurous the middle of a phrase, land its last note on a chord tone. The landing is what the congregation remembers." },
        ],
        practice: [
          "Over a slow chord loop, play one two-second phrase per chord, then rest for the remainder.",
          "Play a 'question' phrase ending on a non-home note, then answer it landing on the key's home note.",
          "Take one phrase and vary it three ways: change its rhythm, its last note, and its octave.",
          "Improvise a full minute using only three different notes. Constraint builds taste.",
        ],
        playAlong: "Loop 1-5-6-4 in G and trade with yourself: two bars of lead, two bars of listening. The listening bars are part of the music.",
        tip: "The rests are the music. A lead line that leaves space feels far more worshipful than constant noodling.",
        theory: "A musical phrase works like a sentence: an antecedent (question) creates tension by ending off the tonic, and a consequent (answer) resolves it by landing on the tonic — the same tension-and-release that drives chord progressions, played out in melody.",
      },
    ],
  },
  {
    id: "m5",
    num: 5,
    title: "Leading Worship",
    subtitle: "The heart & craft of leading worship",
    lessons: [
      {
        id: "m5l1",
        title: "Dynamics & Feel",
        subtitle: "When to build and when to rest",
        minutes: 14,
        objective: "Shape a song's energy with your playing, not just your volume.",
        scripture: { text: "A time to keep silence, and a time to speak.", ref: "Ecclesiastes 3:7" },
        progression: { key: "G", degrees: [1, 4, 6, 5] },
        learn: [
          { title: "The arc of a song", body: "Most worship songs breathe: gentle verse, building pre-chorus, full chorus, stripped-back bridge. Your dynamics draw that arc." },
          { title: "Tools for build", body: "Add strings to your strum, strum harder, move from fingerpicking to full strums, or add a driving eighth-note feel to lift energy." },
          { title: "Tools for rest", body: "Drop to the top strings, fingerpick, or leave space entirely. Silence from the guitar can be powerful." },
          { title: "Texture beats volume", body: "Changing WHAT you play moves a room more than playing louder — a shift from strums to single fingerpicked notes is a bigger dynamic than any volume change." },
          { title: "Watch the room", body: "Dynamics follow the congregation, not the chart. If the room is singing out, lift them; if it's praying, get out of the way." },
        ],
        practice: [
          "Play one progression four times, getting fuller each pass, then drop suddenly to a whisper.",
          "Play a verse fingerpicked and the chorus with full strums, back to back, without pausing.",
          "Practice a 'false build': grow for four bars, then pull back instead of peaking. Control is the skill.",
        ],
        playAlong: "Loop a progression and practice building for eight bars, then pulling right back to almost nothing.",
        tip: "The congregation follows the worship team's energy. Learning to build and release is the heart of leading worship from the guitar.",
        theory: "Musicians describe loudness with dynamic levels from pianissimo (very soft) to fortissimo (very loud), but perceived energy also comes from register, density and rhythmic activity. That's why a high, sparse fingerpicked line can feel more intense than a loud strum — you're moving on more than one axis.",
      },
      {
        id: "m5l5",
        title: "The Nashville Number System",
        subtitle: "How worship teams talk",
        minutes: 14,
        objective: "Read and call chord progressions by number in any key.",
        scripture: { text: "I will sing with the spirit, and I will sing with the understanding also.", ref: "1 Corinthians 14:15" },
        learn: [
          { title: "Number the scale", body: "Give each note of the major scale a number, 1 through 7. In G: G=1, A=2, B=3, C=4, D=5, E=6, F#=7. Chords take the number of their root note." },
          { title: "Major and minor by position", body: "In every major key the pattern is identical: chords 1, 4 and 5 are major; 2, 3 and 6 are minor; 7 is diminished. So '6' in G automatically means E minor." },
          { title: "Read a number chart", body: "A chart that says 1 · 5 · 6 · 4 means G-D-Em-C in G, but D-A-Bm-G in D. Same song, same numbers, any key." },
          { title: "Why teams use it", body: "When the singer needs a different key five minutes before the service, nobody rewrites the chart. The numbers don't change — only the key does." },
        ],
        practice: [
          "Write out the chords 1 through 6 in the keys of G, D, A and C from memory, then check them with the Progression Looper's key selector.",
          "Play 1-5-6-4 in G while calling each chord's number out loud.",
          "Now play the same numbers in D without stopping to think: D, A, Bm, G.",
          "Pick any song you know and work out its numbers.",
        ],
        playAlong: "Set the Progression Looper to 1-5-6-4 and switch keys every pass — say the chord names as they light up.",
        tip: "Numbers turn you into the most flexible player on the worship team. Letters describe one key; numbers describe every key at once.",
        theory: "Numbers describe harmonic function, not just position: 1 is home, 5 pulls back toward home, 4 leans away from it, and 6 is home's minor shadow (the relative minor shares two of its three notes with 1). Classical musicians write the same idea in Roman numerals — I, IV, V, vi.",
      },
      {
        id: "m5l6",
        title: "Serving the Singer",
        subtitle: "Keys, ranges & transposing",
        minutes: 13,
        objective: "Choose and change keys so the congregation can actually sing the song.",
        scripture: { text: "O magnify the LORD with me, and let us exalt his name together.", ref: "Psalm 34:3" },
        learn: [
          { title: "Find the ceiling", body: "Every song has a highest note. Congregations are comfortable up to roughly a C or D above middle C — higher than that and the room stops singing and starts listening." },
          { title: "Move the key, not the melody", body: "If the highest note is too high, transpose down until it sits in range. The melody's shape stays identical; only its altitude changes." },
          { title: "Two ways to transpose", body: "Change chord shapes (play in the new key directly), or keep your shapes and capo. The Capo & Keys tool does the math for both instantly." },
          { title: "Speak the team's language", body: "On a worship team, communicate clearly: 'same shapes, capo 2' or 'take it down to G'. Everyone should know the sounding key before the count-off." },
        ],
        practice: [
          "Take a 1-5-6-4 in G and play it in A twice: once with open A-D-E-F#m... shapes, once with G shapes capoed at the 2nd fret. Hear that they match.",
          "Use the Capo & Keys transposer to move G-C-D into Bb, then play it with the suggested capo.",
          "Sing any chorus you know in two keys and notice which one your voice — and the congregation's — prefers.",
        ],
        playAlong: "Pick a song from the Song Library and use Capo & Keys to move it down a whole step, then play the new version.",
        tip: "The best key is almost never the recording's key — professional vocalists sing higher than congregations. Serve the room, not the record.",
        theory: "Transposition shifts every note by the same interval, so all the internal relationships — the numbers — stay identical. That's also why the capo works: it moves the guitar's open strings up in pitch while your hands keep playing the shapes of the old key.",
      },
      {
        id: "m5l2",
        title: "Leading from the Guitar",
        subtitle: "Cueing the team and the room",
        minutes: 15,
        objective: "Guide a song's structure so the worship team and congregation can follow you.",
        scripture: { text: "It came even to pass, as the trumpeters and singers were as one, to make one sound to be heard in praising and thanking the LORD…", ref: "2 Chronicles 5:13" },
        learn: [
          { title: "Set the tempo", body: "Count the worship team in clearly, or start a steady intro so everyone locks to your pulse. You are the clock." },
          { title: "Signal changes", body: "Use simple, visible cues — a nod, a lifted headstock, calling the section name — so the team knows when the chorus or bridge is coming." },
          { title: "Play the map", body: "Know the song's structure cold so you can lengthen a chorus or repeat a bridge in the moment and the team follows your lead." },
          { title: "Breathe with the room", body: "Keep your eyes up. Watching the congregation — not your fretboard — is what turns playing songs into leading worship." },
          { title: "Recover gracefully", body: "When something goes wrong (it will), keep the pulse and simplify: drop to root-note strums until everyone finds each other again. Steadiness is leadership." },
        ],
        practice: [
          "Count a song in out loud — 'one, two, three, four' at the exact tempo — and start playing precisely on the next '1'.",
          "Play a song and, without stopping, decide to repeat the chorus — signal it clearly to an imaginary team.",
          "Practice the 'rescue': mid-song, drop deliberately to single bass notes for two bars, then rebuild.",
          "Play a full song with your eyes closed or fixed on a point across the room — no looking at your hands.",
        ],
        playAlong: "Loop a progression and practice starting, adding a section, and ending cleanly on a single held strum.",
        tip: "Confidence is a gift to your team. Even a simple part played decisively is easier to follow than a fancy one played timidly. And confidence grows in prayer as much as in practice — lead from a prepared heart.",
        theory: "A count-off works because it establishes tempo before the downbeat: one full bar at performance speed gives every musician two pieces of information at once — where beat 1 lands and how fast the beats come. Internalizing tempos (72 vs 80 BPM) is a trainable skill; check yourself against the Metronome daily.",
      },
      {
        id: "m5l7",
        title: "Flowing Between Songs",
        subtitle: "Transitions & medleys",
        minutes: 14,
        objective: "Connect songs into one continuous, prayerful flow with no dead air.",
        scripture: { text: "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.", ref: "Colossians 3:16" },
        learn: [
          { title: "Group by key", body: "Songs in the same key (or close neighbours like G and C) flow into each other naturally. Plan your set so the keys are friendly." },
          { title: "The pivot chord", body: "To move from a song in G to a song in C, land on a G7 — G is the 5 of C, so that one chord swings the door open into the new key." },
          { title: "The instrumental bridge", body: "Between songs, keep a gentle bed going: fingerpick the new song's 1 chord, or vamp 1-4 quietly while the leader prays or speaks." },
          { title: "Capo on the move", body: "If the next song needs a capo change, cover it: let the keys or another guitar hold the space, or end the previous song fully and let silence do its work — a planned silence is a transition too." },
        ],
        practice: [
          "Play the last bar of a song in G, hold a G7, then begin a progression in C. Feel the door open.",
          "Do the same from D into G using a D7.",
          "Practice a two-song medley from the Song Library: end song one, vamp its 1 chord fingerpicked for four bars, then count yourself into song two.",
        ],
        playAlong: "Choose two songs in the Song Library that share a key and practice flowing from the end of one into the start of the other without stopping.",
        tip: "Dead air between songs breaks the room's focus. You don't need to be fancy — a single quiet chord held with intention keeps everyone's hearts in place.",
        theory: "A pivot chord belongs to both the old key and the new one — and the strongest doorway is the new key's 5 chord, especially as a dominant 7th, because its tension resolves squarely onto the new home. That's why G7 walks so inevitably into C.",
      },
      {
        id: "m5l3",
        title: "Spontaneous Worship",
        subtitle: "Playing in open, unscripted moments",
        minutes: 15,
        objective: "Hold an open, prayerful musical space with just a chord or two.",
        scripture: { text: "Be still, and know that I am God.", ref: "Psalm 46:10" },
        progression: { key: "D", degrees: [1, 4] },
        learn: [
          { title: "Pick a home", body: "Spontaneous moments often live on one or two chords (a 1-4 vamp). Choose a key and settle in." },
          { title: "Less is more", body: "Gentle fingerpicking, a slow swell, or a single sustained chord creates space for prayer and singing." },
          { title: "Follow the leader", body: "Watch the worship leader and the room. Rise when they rise, soften when they soften — you're accompanying a conversation with God." },
          { title: "Rotate your textures", body: "Cycle slowly between fingerpicked arpeggios, soft strums, and harmonized thirds high on the neck. Variety without change — same chords, new colors." },
          { title: "Leave and return", body: "It's okay to stop playing entirely for a few bars. Re-entering gently is one of the most powerful dynamics you own." },
        ],
        practice: [
          "Fingerpick a 1-4 vamp in D very slowly for two minutes without rushing.",
          "Hold a single chord and swell it in and out for one minute, listening more than playing.",
          "Cycle three textures over the vamp — arpeggios, soft strums, thirds — spending 30 seconds in each.",
        ],
        playAlong: "Loop a 1-4 vamp at a slow tempo and practice adding and removing texture without ever changing the chords.",
        tip: "In these moments your job is to get out of the way. A simple, steady bed of sound lets the room encounter God.",
        theory: "The 1-4 movement is plagal motion — the sound of the sung 'Amen' at the end of old hymns. Unlike the 5-1 cadence, which demands resolution, 4 to 1 relaxes into it, which is why the vamp can cycle for minutes without feeling like it needs to go anywhere.",
      },
      {
        id: "m5l8",
        title: "Solo Classical Worship",
        subtitle: "Bass, harmony & melody together",
        minutes: 18,
        objective: "Arrange and play a hymn as a complete solo classical guitar piece.",
        scripture: { text: "I will also praise thee with the psaltery, even thy truth, O my God: unto thee will I sing with the harp, O thou Holy One of Israel.", ref: "Psalm 71:22" },
        learn: [
          { title: "One guitar, three voices", body: "This is the classical guitar's superpower: the thumb plays the bass, the fingers carry the melody on the top strings, and the harmony rings in between." },
          { title: "The thumb keeps the floor", body: "Play each chord's root on beat 1 with p — G under the G chord, C under the C chord. The bass note anchors everything above it." },
          { title: "Melody on top", body: "Put the tune on the highest voice with rest strokes where possible so it sings above the accompaniment. Start with the first phrase of 'Amazing Grace'." },
          { title: "Fill the middle sparingly", body: "Between melody notes, brush a partial chord or add one inner-voice note. The middle voice supports; it must never crowd the tune." },
          { title: "Let it breathe", body: "Solo playing doesn't need a fixed pulse — this is rubato, borrowed time. Stretch a phrase's peak, ease into its close, like a singer would." },
        ],
        practice: [
          "Play just the bass notes of Amazing Grace's chords in 3/4 — root on beat 1, silence on 2 and 3.",
          "Play just the melody of the first phrase on the top strings, with rest strokes.",
          "Combine them: bass on beat 1 with p, melody on top. One phrase only, very slowly.",
          "When one phrase works, add the next. A verse of this is a genuine offertory piece.",
        ],
        playAlong: "Play your solo arrangement of Amazing Grace's first phrase over the Song Library chart to check the harmony matches, then perform it alone, freely.",
        tip: "This is where classical technique becomes ministry — a single nylon-string guitar holding a room in stillness. Take months over this skill; it's worth years.",
        theory: "You're writing three-voice counterpoint: bass, inner harmony, and melody moving with rhythmic independence. The thumb's alternating bass is doing what a keyboardist's left hand does — and because the ear tracks the outer voices (bass and melody) most strongly, keeping those two clean matters more than anything in the middle.",
      },
      {
        id: "m5l4",
        title: "Leading a Full Set",
        subtitle: "Planning and carrying a worship set",
        minutes: 20,
        objective: "Plan and play a short set of songs that flows as one journey.",
        scripture: { text: "So he fed them according to the integrity of his heart; and guided them by the skilfulness of his hands.", ref: "Psalm 78:72" },
        learn: [
          { title: "Order for flow", body: "Group songs by key and tempo so transitions are smooth. A common arc: an upbeat opener, into mid-tempo, into an intimate closer." },
          { title: "Connect the songs", body: "Use a shared key, a pivot chord, or a capo change to glide from one song into the next without dead air — everything from the transitions lesson, now with a plan." },
          { title: "Plan the dynamics", body: "Decide where the set builds and where it rests, so the whole thing has one shape, not four separate songs." },
          { title: "Write the map", body: "Note each song's key, capo, tempo and the transition into the next. One index card holds a whole set — and frees your eyes for the room." },
          { title: "Pray it through", body: "A set list is a prayer plan. Play it through once alone, asking where the room will need to sing, to shout, and to be still." },
        ],
        practice: [
          "Choose three songs from the Song Library and put them in an order that flows by key and tempo.",
          "Write the map: key, capo, tempo, and the transition chord between each pair.",
          "Play the full set alone, top to bottom, including the transitions — no stopping between songs.",
          "Play it again and deliberately change one thing in the moment (repeat a chorus, extend a vamp) to practice flexibility.",
        ],
        playAlong: "Use the Song Library charts to play your three-song set back to back, keeping the pulse steady between songs.",
        tip: "You've come the whole journey — from your first note to leading a set. Keep serving, keep growing, and play skilfully for the Lord.",
        theory: "Set keys work like a journey on the circle of fifths: neighbouring keys (G-C-D, or D-A-G) share most of their notes, so moving between them feels seamless, while a distant key change reads as a deliberate 'lift'. Tempo works the same way — congregations follow gradual changes and feel sudden ones.",
      },
    ],
  },
];

// Kickers are derived from array position so lessons can be reordered freely.
MODULES.forEach((m) => {
  m.lessons.forEach((l, i) => {
    l.kicker = `Module ${m.num} · Lesson ${i + 1}`;
  });
});

export const ALL_LESSONS: Lesson[] = MODULES.flatMap((m) => m.lessons);

export function lessonById(id: string): { lesson: Lesson; module: Module } | null {
  for (const m of MODULES) {
    const l = m.lessons.find((x) => x.id === id);
    if (l) return { lesson: l, module: m };
  }
  return null;
}
